{
  # microlith's pinned toolchain. Lives at the repo ROOT, which is not
  # decoration: a flake's source root is its own directory, so a flake in a
  # subdirectory cannot see `Cargo.toml`/`src/` and can offer no package at
  # all. Root is also every Rust project's shape, so it needs no teaching.
  #
  # Pinned to the same nixpkgs revision as itok, the first consumer, so the
  # two repos cannot drift into different rustc/clippy versions and
  # disagree about a verdict.
  description = "microlith -- the cavekit SPEC format, enforced (dev shell)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/241313f4e8e508cb9b13278c2b0fa25b9ca27163";

  outputs =
    { nixpkgs, ... }:
    let
      systems = [
        "aarch64-darwin"
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAll = f: nixpkgs.lib.genAttrs systems (s: f nixpkgs.legacyPackages.${s});

      # microlith formats its own SPEC.md (V24), so the dev shell must PROVIDE
      # `microlith`, not merely the toolchain to build it.
      #
      # Deliberately a SHIM rather than a package in the shell's closure: a
      # package has to BUILD the crate in order to enter the shell, so one
      # compile error locks you out of the shell you need to fix it. And a
      # built package is stale against the working tree, while `cargo run`
      # is a no-op when fresh and rebuilds only on change -- so the shim
      # always matches the source you are editing, which is the whole point
      # of dogfooding.
      microlithShim =
        pkgs:
        pkgs.writeShellScriptBin "mth" ''
          set -eu
          manifest="''${MICROLITH_MANIFEST:-}"
          if [ -z "$manifest" ] || [ ! -f "$manifest" ]; then
            echo "mth(shim): MICROLITH_MANIFEST unset or missing -- re-enter the dev shell from the repo root" >&2
            exit 2
          fi
          profile=""
          [ "''${MICROLITH_PROFILE:-debug}" = "release" ] && profile="--release"
          exec cargo run --quiet $profile \
            --manifest-path "$manifest" --bin mth -- "$@"
        '';

      # A git hook, written BY HAND rather than by `hk install` (V23).
      #
      # An installer writes a command that assumes its own binary is on
      # PATH. Outside this shell it is not, so an installed hook would make
      # every git command in the repo FAIL rather than merely run ungated.
      # This one tests for the runner first and degrades LOUDLY: one line to
      # stderr, exit 0. A gate exists to stop bad commits, not to stop git --
      # and the LOUD line is the whole safety margin, because the hooks ARE
      # the gate of record (V22) and nothing downstream catches what they
      # skip (V23, B19).
      #
      # Materialized through the store, then COPIED into `.git/hooks` rather
      # than symlinked: a symlink into the store dangles after a GC, and a
      # dangling hook makes git error out -- the exact hard failure this
      # whole design exists to avoid. The shebang is `/bin/sh`, not a store
      # path, for the same reason.
      gitHook =
        pkgs: name:
        pkgs.writeText "microlith-${name}-hook" ''
          #!/bin/sh
          # Generated by microlith's dev shell (flake.nix), rewritten on every
          # entry. Edit the shellHook there, not this copy.
          #
          # PRESENT TENSE, earned. This said "CI WILL gate" while ci.yml had
          # run zero times, and promised the change the moment it had -- so
          # here it is: run 30763172352, green on ubuntu-latest,
          # ubuntu-24.04-arm and macos-latest, the first execution ever. It
          # is also now REQUIRED: all three jobs are branch-protection status
          # checks on main, enforced for admins, so nothing merges without
          # them (B19).
          command -v hk >/dev/null 2>&1 || {
            echo "hk: not on PATH -- SKIPPING the ${name} gate. Enter the dev shell (\`direnv allow\` or \`nix develop\`) to run it locally; CI gates regardless." >&2
            exit 0
          }
          exec hk run ${name} "$@"
        '';

      # The reproducible build. Possible because the flake sits at the root
      # and `Cargo.lock` is tracked -- flakes copy git-TRACKED files into
      # the store, and the build sandbox has no network, so the lock is what
      # lets nix vendor crates offline. microlith has zero dependencies, so
      # there is nothing to vendor today; the lock still matters, because
      # the guarantee should not depend on staying dependency-free.
      microlithPkg =
        pkgs:
        pkgs.rustPlatform.buildRustPackage {
          pname = "microlith";
          # Read from Cargo.toml so there is ONE version, never two that can
          # disagree.
          version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package.version;
          # Only what the BUILD reads. With `src = ./.` every tracked file is
          # an input, so editing SPEC.md would rebuild the crate from
          # scratch -- which for a tool whose job is editing SPEC.md would be
          # a rebuild on nearly every commit.
          src = pkgs.lib.fileset.toSource {
            root = ./.;
            fileset = pkgs.lib.fileset.unions [
              ./src
              ./Cargo.toml
              ./Cargo.lock
            ];
          };
          cargoLock.lockFile = ./Cargo.lock;
          # `tests/dogfood.rs` reads SPEC.md, which is deliberately NOT in
          # the fileset above. So the dogfood cannot run here; it runs in the
          # dev shell and in CI, where the whole tree exists. Excluding the
          # spec from the build inputs and running its test elsewhere is the
          # same tradeoff seen from both sides.
          doCheck = false;
          meta = {
            description = "enforce the cavekit SPEC format: lossless minify, structural check, CPU only";
            homepage = "https://github.com/pr0d1r2/microlith";
            license = pkgs.lib.licenses.mit;
            mainProgram = "mth";
          };
        };
    in
    {
      packages = forAll (pkgs: {
        default = microlithPkg pkgs;
      });

      devShells = forAll (pkgs: {
        default = pkgs.mkShell {
          packages = [
            (microlithShim pkgs)
            pkgs.rustc
            pkgs.cargo
            pkgs.clippy
            pkgs.rustfmt
            pkgs.cargo-nextest
            pkgs.cargo-llvm-cov
            pkgs.llvmPackages.llvm
            pkgs.git
            # The gate runner; the ops it runs live in `hk.pkl`.
            pkgs.hk
            # Gate steps that need a real binary, pinned here so the dev
            # shell and CI run identical versions rather than whatever each
            # happened to install.
            pkgs.typos
            pkgs.taplo
            # `nixfmt --check` gates this very file: the flake decides what
            # every other step runs with, so drift here is drift everywhere.
            pkgs.nixfmt
            # `ci.yml` is the ONE file no local step exercises, so without
            # this a mistake there is found only by pushing. It arrives now
            # that the workflow really runs, and not before.
            pkgs.actionlint
            # Relative links break when a file MOVES, and nothing else here
            # would notice: eleven docs carry 31 of them, and two directory
            # moves rewrote them in both directions. Run `--offline` so the
            # gate never reaches the network -- the 37 external URLs are a
            # different problem with a different failure mode, and someone
            # else's 404 must not fail your commit.
            pkgs.lychee
            # Secrets, BESIDE `no-private-key` rather than instead of it:
            # `hk util detect-private-key` does exactly what its name says
            # and nothing else -- MEASURED, an `AWS_SECRET_ACCESS_KEY=...`
            # line walks straight past it. ripsecrets covers the token
            # shapes it cannot. Rust, and in nixpkgs, so it pins here like
            # every other linter rather than arriving by a second path.
            #
            # hk ships a `betterleaks` builtin that would also do this, but
            # it is NOT packaged -- using it would mean an install path
            # outside this shell, which is the skew ci.yml exists to avoid.
            pkgs.ripsecrets
            # The supply chain, in ONE tool. cargo-audit and osv-scanner ask
            # the advisories question this already answers; three tools for
            # one question is the shape V7 exists to prevent.
            pkgs.cargo-deny
            # The VERSION LADDER, mechanically. V30 says which rung means
            # what and V34 splits even from odd, but until now the only
            # thing standing between a breaking change and a minor bump was
            # somebody remembering. This diffs the pub API (V32) against the
            # last published release and names what broke.
            #
            # It cannot run before there IS a published release, and it says
            # so rather than passing quietly -- see the step in hk.pkl.
            pkgs.cargo-semver-checks
          ];
          # Pin locale so tool output is deterministic across machines.
          LANG = "C.UTF-8";
          LLVM_COV = "${pkgs.llvmPackages.llvm}/bin/llvm-cov";
          LLVM_PROFDATA = "${pkgs.llvmPackages.llvm}/bin/llvm-profdata";
          # Resolved at ENTRY rather than baked in: `.envrc` sits beside
          # `Cargo.toml` and direnv enters with PWD set to that directory,
          # so this works wherever the repo is checked out. Derive, never
          # hardcode a path.
          #
          # Entering also installs the git hooks, unconditionally rewriting
          # them, so the hook a contributor has is always the one this file
          # describes -- editing the hook needs no separate reinstall step
          # to take effect, which is how an installed hook goes stale.
          #
          # `git rev-parse --git-path hooks` rather than a literal
          # `.git/hooks`: in a worktree or a submodule `.git` is a FILE and
          # the real hooks directory is elsewhere, so the literal path
          # silently installs nothing.
          shellHook = ''
            if [ -f "$PWD/Cargo.toml" ]; then
              export MICROLITH_MANIFEST="$PWD/Cargo.toml"
            else
              echo "microlith(shell): no Cargo.toml in $PWD -- \`mth\` shim disabled" >&2
            fi

            microlith_hooks="$(git rev-parse --git-path hooks 2>/dev/null || true)"
            if [ -n "$microlith_hooks" ] && [ -d "$microlith_hooks" ]; then
              install -m 755 ${gitHook pkgs "pre-commit"} "$microlith_hooks/pre-commit"
              install -m 755 ${gitHook pkgs "pre-push"} "$microlith_hooks/pre-push"
            else
              echo "microlith(shell): no git hooks directory -- hooks not installed, so nothing is gating (V22)" >&2
            fi
            unset microlith_hooks
          '';
        };
      });
    };
}
